# Generated by Django 3.1.6 on 2022-05-16 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.IntegerField(choices=[(1, 'PANELTIES'), (2, 'LEAD CHARGES'), (3, 'SERVICE CHARGES'), (4, 'VENDOR SEARCH'), (5, 'VOLUNTEERS'), (6, 'JOB CREATION')]),
        ),
    ]
