# Generated by Django 3.1.6 on 2022-05-16 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0003_remove_document_review'),
        ('transactions', '0002_auto_20220515_2237'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
