# Generated by Django 3.1.6 on 2022-05-16 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_auto_20220515_2237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='seen_by_client',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='seen_by_vendor',
        ),
    ]
